name: shuttertop
description: Contest fotografici improvvisati e via discorrendo 

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  http: '^0.12.0'
  google_sign_in: "^4.0.0"
  shared_preferences: '^0.4.0'
  timeago: "^2.0.10"
  image_picker: #"^0.4.8"
    git:
      url: git://github.com/romaluca/plugins.git
      path: packages/image_picker
    #path: ../plugins/packages/image_picker
  crypto: "^2.0.6"
  share: "^0.6.0"
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: e69fef3
  flutter_launcher_icons: "^0.6.1"
  firebase_core: ^0.3.0
  firebase_messaging: #"^2.0.0"
    git:
      url: git://github.com/romaluca/plugins.git
      path: packages/firebase_messaging
    #path: ../plugins/packages/firebase_messaging
  firebase_admob: ^0.8.0
  cached_network_image: ^0.6.0+1
  # firebase_analytics: "^1.1.0"
  package_info: "^0.4.0"
  url_launcher: "^5.0.0"
  sticky_headers: "^0.1.7"
  uni_links: "^0.1.4"
  sentry: any 
  flutter_circular_chart: "^0.1.0"
  transparent_image: ^0.1.0
  flutter_local_notifications: "^0.5.0"
  flutter_spotlight: "^0.1.1"
  exif_flutter:
    git:
      url: git://github.com/romaluca/exif_flutter.git
      #path: ../exif_flutter
  event_bus: ^1.0.1
  shimmer: ^1.0.0
  flutter_svg: ^0.10.3
  webview_flutter: ^0.3.0
  translator: ^0.1.0+5
  font_awesome_flutter: ^8.4.0
  outline_material_icons: ^0.1.0





dev_dependencies:
  intl_translation: "^0.17.2"
  #flutter_test:
  #  sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    #- family: Ionicons # Do not change!
    #  fonts:
    #    - asset: assets/fonts/ionicons.woff
    - family: Raleway
      fonts:
        - asset: assets/fonts/rawline-400.ttf
        - asset: assets/fonts/rawline-500.ttf
        - asset: assets/fonts/rawline-600.ttf
        - asset: assets/fonts/rawline-700.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        # - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
  assets:
    - assets/images/logo.svg
    - assets/images/placeholder.png
    - assets/images/1x1_transparent.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/award.svg
    - assets/images/rays.svg
flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: false

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
